### ISSUE TITLE
We should do a safer default configuration for launched instances

### ISSUE THREAD

**Issue by jameinel** [jnsgruk/zinc-k8s-operator#295]
https://github.com/jnsgruk/zinc-k8s-operator/blob/9cd0ae62b3f970bb04042f4314d02fec74833033/tests/spread/cloud-config.yaml#L7-L10

I realize it matters a little bit less for containers that you launch on your lxd instances, but this seems like a bad default for anything that we are running on external infrastructure (and hygiene says we shouldn't really do it locally, either).

I don't understand the options and tools sufficiently at this point to know how to do better here, but as we are establishing patterns this seems like an important want to avoid other teams cribbing.

**Comment by jnsgruk** [comment]
In reality, the machines allocated by spread are often local to the test machine (in the case of LXD VMs), though that can vary. In the case of the Github Actions backend `github-ci`, the machines are not publicly routable.

That said, I agree that we can do better. #297 addresses this by using a randomly generated password for each invocation. Sadly no ability to specify an SSH key for `spread` to use at this stage (my initial prototype was generating a new key each time, but that didn't work out).
